name: Actions Workflow
on: [push, pull_request]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: List files
        run: |
          pwd
          ls -a
          echo "${{ github.token }}"

      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Jhon

      - name: Log Greetings Time
        run: echo "${{ steps.greet.outputs.time }}"

