name: Create artifacts

on: [pull_request, push]

env:
  tag: v1.2.9

jobs:

  get-package-version:
    name: Get package version
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        run: |
          export PACKAGE_VERSION=`node -p "require('./package.json').version"`;

  create-artifacts:
    runs-on: ubuntu-latest
    name: Create artifact
    needs: [get-package-version]
    env:
      tag: $PACKAGE_VERSION
    steps:
      - run: echo $tag
      - uses: actions/checkout@v3
      - run: mkdir -p path/to/artifact
      - run: echo $tag > path/to/artifact/artifact-$tag.txt
      - run: ls -al path/to/artifact
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact-${{env.tag}}
          path: path/to/artifact/artifact-${{env.tag}}.txt

  test-artifact:
    name: Test artifacts
    runs-on: ubuntu-latest
    needs: [create-artifacts]
    env:
      tag: v1.2.9
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact-${{env.tag}}
          path: path/to/artifact

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: path/to/artifact

      - name: Show text artifact
        run: cat artifact-${tag}.txt
        working-directory: path/to/artifact
