name: release-workflow

on:
  push:
    branches:
      - main
env:
  tag: v1.2.9

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      tag: v1.2.9
    steps:
      - uses: actions/checkout@v3
      # Do not have access to other WF artifacts
      # - uses: actions/download-artifact@v3
      #   with:
      #     name: my-artifact
      #     path: dist
      # - name: Display structure of downloaded files
      #   run: ls -R
      #   working-directory: dist
      - run: mkdir -p dist
      - run: echo $ART_VERSION
      - name: Download artifacts
        run: gh run download -n my-artifact-$tag
        working-directory: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Display structure of downloaded files
        run: ls -R
      - name: Create a tag
        run: |
          echo "Creating git tag:" $tag
          git config --local user.name "bsekula"
          git config --local user.email "bsekula12@gmail.com"
          git tag -a $tag -m "$tag test"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git push origin --tags

      - name: Release by softprops
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/*
          tag_name: $tag

      # - name: Release
      #   run: gh release create v1.2.3 ./dist/*
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}





