name: Test interpolation

on: push


jobs:

  create-outputs:
    runs-on: ubuntu-latest
    name: Create ls flag
    steps:
      - id: step1
        run: |
          echo "LS_FLAG=-als" >> "$GITHUB_ENV"

  test-ls:
    runs-on: ubuntu-latest
    name: Test ls

    steps:
      - run: echo $tag
      - uses: actions/checkout@v3
      - run: mkdir -p aaaa
      - run: mkdir -p bbbb
      - run: ls -alt
      - name: test interpolation
        run: ls ${{env.LS_FLAG}} .
      - name: test interpolation
        run: echo ${{env}}
